# Copyright (C) 2022 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
{{- if .Values.edgex.storage.useHostPath }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: edgex-consul-config-volume
spec:
  storageClassName: ""
  claimRef:
    name: consul-config
    namespace: {{ .Release.Namespace }}
  capacity:
    storage: 500Mi
  accessModes:
    - {{.Values.edgex.storage.nonSharedVolumesAccessMode}}
  hostPath:
    path: "/mnt/edgex-consul-config"
{{- end}}
---
{{- if .Values.edgex.storage.useHostPath }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: edgex-consul-data-volume
spec:
  storageClassName: ""
  claimRef:
    name: consul-data
    namespace: {{ .Release.Namespace }}
  capacity:
    storage: 500Mi
  accessModes:
    - {{.Values.edgex.storage.nonSharedVolumesAccessMode}}
  hostPath:
    path: "/mnt/edgex-consul-data"
{{- end }}
---
{{- if .Values.edgex.storage.useHostPath }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: edgex-db-volume
spec:
  storageClassName: ""
  claimRef:
    name: db-data
    namespace: {{ .Release.Namespace }}
  capacity:
    storage: 1Gi
  accessModes:
    - {{.Values.edgex.storage.nonSharedVolumesAccessMode}}
  hostPath:
    path: "/mnt/edgex-db"
{{- end }}
---
{{- if .Values.edgex.storage.useHostPath }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: edgex-kuiper-data
spec:
  storageClassName: ""
  claimRef:
    name: kuiper-data
    namespace: {{ .Release.Namespace }}
  capacity:
    storage: 128Mi
  accessModes:
    - {{.Values.edgex.storage.nonSharedVolumesAccessMode}}
  hostPath:
    path: "/mnt/edgex-kuiper-data"
{{- end }}
---
{{- if .Values.edgex.storage.useHostPath }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: edgex-secrets-volume
spec:
  storageClassName: ""
  claimRef:
    name: edgex-secrets
    namespace: {{ .Release.Namespace }}
  capacity:
    storage: 8Mi
  accessModes:
    - {{.Values.edgex.storage.sharedVolumesAccessMode}}
  hostPath:
    path: "/tmp/edgex/secrets"
{{- end }}
---
{{- if .Values.edgex.storage.useHostPath }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: edgex-init-volume
spec:
  storageClassName: ""
  claimRef:
    name: edgex-init
    namespace: {{ .Release.Namespace }}
  capacity:
    storage: 128Mi
  accessModes:
    - {{.Values.edgex.storage.sharedVolumesAccessMode}}
  hostPath:
    path: "/mnt/edgex-init-volume"
{{- end }}
---
{{- if .Values.edgex.storage.useHostPath }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: edgex-vault-data-volume
spec:
  storageClassName: ""
  claimRef:
    name: vault-file
    namespace: {{ .Release.Namespace }}
  capacity:
    storage: 1Gi
  accessModes:
    - {{.Values.edgex.storage.nonSharedVolumesAccessMode}}
  hostPath:
    path: "/mnt/edgex-vault-data"
{{- end }}
---
{{- if .Values.edgex.storage.useHostPath }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: edgex-vault-logs-volume
spec:
  storageClassName: ""
  claimRef:
    name: vault-logs
    namespace: {{ .Release.Namespace }}
  capacity:
    storage: 1Gi
  accessModes:
    - {{.Values.edgex.storage.nonSharedVolumesAccessMode}}
  hostPath:
    path: "/mnt/edgex-vault-logs"
{{- end }}
---
{{- if .Values.edgex.storage.useHostPath }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: edgex-vault-config-volume
spec:
  storageClassName: ""
  claimRef:
    name: vault-config
    namespace: {{ .Release.Namespace }}
  capacity:
    storage: 8Mi
  accessModes:
    - {{.Values.edgex.storage.nonSharedVolumesAccessMode}}
  hostPath:
    path: "/mnt/edgex-vault-config"
{{- end }}
---
{{- if .Values.edgex.storage.useHostPath }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: edgex-redis-config-volume
spec:
  storageClassName: ""
  claimRef:
    name: redis-config
    namespace: {{ .Release.Namespace }}
  capacity:
    storage: 8Mi
  accessModes:
    - {{.Values.edgex.storage.nonSharedVolumesAccessMode}}
  hostPath:
    path: "/mnt/edgex-redis-config"
{{- end }}
---
{{- if .Values.edgex.storage.useHostPath }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: edgex-consul-acl-token-volume
spec:
  storageClassName: ""
  claimRef:
    name: consul-acl-token
    namespace: {{ .Release.Namespace }}
  capacity:
    storage: 8Mi
  accessModes:
    - {{.Values.edgex.storage.nonSharedVolumesAccessMode}}
  hostPath:
    path: "/mnt/edgex-consul-acl-token"
{{- end }}
---
{{- if .Values.edgex.storage.useHostPath }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: edgex-device-onvif-camera
spec:
  storageClassName: ""
  claimRef:
    name: device-onvif-camera
    namespace: {{ .Release.Namespace }}
  capacity:
    storage: 128Mi
  accessModes:
    - {{.Values.edgex.storage.nonSharedVolumesAccessMode}}
  hostPath:
    path: "/mnt/edgex-device-onvif-camera"
{{- end}}
---
{{- if .Values.edgex.storage.useHostPath }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: edgex-device-usb-camera
spec:
  storageClassName: ""
  claimRef:
    name: device-usb-camera
    namespace: {{ .Release.Namespace }}
  capacity:
    storage: 128Mi
  accessModes:
    - {{.Values.edgex.storage.nonSharedVolumesAccessMode}}
  hostPath:
    path: "/mnt/edgex-device-usb-camera"
{{- end}}
---
{{- if .Values.edgex.storage.useHostPath }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: edgex-app-rfid-llrp-inventory
spec:
  storageClassName: ""
  claimRef:
    name: app-rfid-llrp-inventory
    namespace: {{ .Release.Namespace }}
  capacity:
    storage: 128Mi
  accessModes:
    - {{.Values.edgex.storage.nonSharedVolumesAccessMode}}
  hostPath:
    path: "/mnt/edgex-app-rfid-llrp-inventory"
{{- end}}