# Copyright (C) 2022 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consul-config
spec:
  storageClassName: "{{.Values.edgex.storage.className}}"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consul-data
spec:
  storageClassName: "{{.Values.edgex.storage.className}}"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data
spec:
  storageClassName: "{{.Values.edgex.storage.className}}"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kuiper-data
spec:
  storageClassName: "{{.Values.edgex.storage.className}}"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
{{- if .Values.edgex.security.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edgex-secrets
spec:
  storageClassName: "{{.Values.edgex.storage.className}}"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edgex-init
spec:
  storageClassName: "{{.Values.edgex.storage.className}}"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-file
spec:
  storageClassName: "{{.Values.edgex.storage.className}}"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-logs
spec:
  storageClassName: "{{.Values.edgex.storage.className}}"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-config
spec:
  storageClassName: "{{.Values.edgex.storage.className}}"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-config
spec:
  storageClassName: "{{.Values.edgex.storage.className}}"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consul-acl-token
spec:
  storageClassName: "{{.Values.edgex.storage.className}}"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Mi
{{- end }}
