# Copyright (C) 2022 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.system}}
  name: {{.Values.edgex.app.system}}
spec:
  replicas: {{.Values.edgex.replicas.system}}
  selector:
    matchLabels:
      org.edgexfoundry.service: {{.Values.edgex.app.system}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        org.edgexfoundry.service: {{.Values.edgex.app.system}}
    spec:
    {{- if and (eq .Values.edgex.security.enabled true) (eq .Values.edgex.storage.isLocal true)}}
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  org.edgexfoundry.service: {{ .Values.edgex.app.secretstoresetup}}
              topologyKey: "kubernetes.io/hostname"
    {{- end}}
      automountServiceAccountToken: false
      containers:
      - name: {{.Values.edgex.app.system}}
        image: {{.Values.edgex.image.system.repository}}:{{.Values.edgex.image.system.tag}}
        imagePullPolicy: {{.Values.edgex.image.system.pullPolicy}}
      {{- if .Values.edgex.security.enabled }}
        command: ["/edgex-init/ready_to_run_wait_install.sh"]
        args: ["/sys-mgmt-agent", "-cp=consul.http://edgex-core-consul:8500", "--registry", "--confdir=/res"]
      {{- end}}
        ports:
        - containerPort: {{.Values.edgex.port.system}}
      {{- if not .Values.edgex.security.enabled }}
          hostPort: {{.Values.edgex.port.system}}
          hostIP: {{.Values.edgex.hostPortInternalBind}}
      {{- end}}
        envFrom:
        - configMapRef:
            name: edgex-common-variables
        env:
        - name: SERVICE_HOST
          value: {{.Values.edgex.app.system}}
        - name: EXECUTORPATH
          value: "/sys-mgmt-executor"
        - name: METRICSMECHANISM
          value: "executor"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        startupProbe:
          httpGet:
            path: /api/v2/ping
            port: {{.Values.edgex.port.system}}
          periodSeconds: 1
          failureThreshold: 120
        livenessProbe:
          httpGet:
            path: /api/v2/ping
            port: {{.Values.edgex.port.system}}
      {{- if .Values.edgex.security.enabled }}
        volumeMounts:
        - mountPath: /edgex-init
          name: edgex-init
        - mountPath: /tmp/edgex/secrets
          name: edgex-secrets
      {{- end }}
      {{- if .Values.edgex.resources.system.enforceLimits }}
        resources:
          limits:
            memory: {{ .Values.edgex.resources.system.limits.memory }}
            cpu: {{ .Values.edgex.resources.system.limits.cpu }}
          requests:
            memory: {{ .Values.edgex.resources.system.requests.memory }}
            cpu: {{ .Values.edgex.resources.system.requests.cpu }}
      {{- end}}
      hostname: {{.Values.edgex.app.system}}
      restartPolicy: Always
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        seLinuxOptions:
          # needed for CentOS to provide docker access (note: Kubernetes on docker is deprecated)
          level: "s0-s0:c0.c1023"
          user: "unconfined_u"
          role: "unconfined_r"
    {{- if .Values.edgex.security.enabled }}
      volumes:
      - name: edgex-init
        persistentVolumeClaim:
          claimName: edgex-init
      - name: edgex-secrets
        persistentVolumeClaim:
          claimName: edgex-secrets
    {{- end}}