# Copyright (C) 2022 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.appservice.rules}}
  name: {{.Values.edgex.app.appservice.rules}}
spec:
  replicas: {{.Values.edgex.replicas.appservice.rules}}
  selector:
    matchLabels:
      org.edgexfoundry.service: {{.Values.edgex.app.appservice.rules}}
  strategy: {}
  template:
    metadata:
      labels:
        org.edgexfoundry.service: {{.Values.edgex.app.appservice.rules}}
    spec:
    {{- if and (eq .Values.edgex.security.enabled true) (eq .Values.edgex.storage.isLocal true)}}
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  org.edgexfoundry.service: {{ .Values.edgex.app.secretstoresetup}}
              topologyKey: "kubernetes.io/hostname"
    {{- end}}
      automountServiceAccountToken: false
      containers:
      - name: {{.Values.edgex.app.appservice.rules}}
        image: {{.Values.edgex.image.appservice.rules.repository}}:{{.Values.edgex.image.appservice.rules.tag}}
        imagePullPolicy: {{.Values.edgex.image.appservice.rules.pullPolicy}}
      {{- if .Values.edgex.security.enabled }}
        command: ["/edgex-init/ready_to_run_wait_install.sh"]
        args: ["/app-service-configurable", "-cp=consul.http://edgex-core-consul:8500", "--registry", "--confdir=/res"]
      {{- end}}
        ports:
        - containerPort: {{.Values.edgex.port.appservice.rules}}
      {{- if not .Values.edgex.security.enabled }}
          hostPort: {{.Values.edgex.port.appservice.rules}}
          hostIP: {{.Values.edgex.hostPortInternalBind}}
      {{- end}}
        envFrom:
        - configMapRef:
            name: edgex-common-variables
        env:
        - name: EDGEX_PROFILE
          value: "rules-engine"
        - name: SERVICE_HOST
          value: {{.Values.edgex.app.appservice.rules}}
        - name: TRIGGER_EDGEXMESSAGEBUS_PUBLISHHOST_HOST
          value: {{.Values.edgex.app.redis}}
        - name: TRIGGER_EDGEXMESSAGEBUS_SUBSCRIBEHOST_HOST
          value: {{.Values.edgex.app.redis}}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        startupProbe:
          httpGet:
            path: /api/v2/ping
            port: {{.Values.edgex.port.appservice.rules}}
          periodSeconds: 1
          failureThreshold: 120
        livenessProbe:
          httpGet:
            path: /api/v2/ping
            port: {{.Values.edgex.port.appservice.rules}}
      {{- if .Values.edgex.security.enabled }}
        volumeMounts:
        - mountPath: /edgex-init
          name: edgex-init
        - mountPath: /tmp/edgex/secrets
          name: edgex-secrets
      {{- end }}
      {{- if .Values.edgex.resources.appservice.rules.enforceLimits }}
        resources:
          limits:
            memory: {{ .Values.edgex.resources.appservice.rules.limits.memory }}
            cpu: {{ .Values.edgex.resources.appservice.rules.limits.cpu }}
          requests:
            memory: {{ .Values.edgex.resources.appservice.rules.requests.memory }}
            cpu: {{ .Values.edgex.resources.appservice.rules.requests.cpu }}
      {{- end}}
      hostname: {{.Values.edgex.app.appservice.rules}}
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        runAsUser: {{ .Values.edgex.security.runAsUser }}
        runAsGroup: {{ .Values.edgex.security.runAsGroup }}
    {{- if .Values.edgex.security.enabled }}
      volumes:
      - name: edgex-init
        persistentVolumeClaim:
          claimName: edgex-init
      - name: edgex-secrets
        persistentVolumeClaim:
          claimName: edgex-secrets
    {{- end}}
