# Copyright (C) 2022 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.device.mqtt}}
  name: {{.Values.edgex.app.device.mqtt}}
spec:
  replicas: {{.Values.edgex.replicas.device.mqtt}}
  selector:
    matchLabels:
      org.edgexfoundry.service: {{.Values.edgex.app.device.mqtt}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        org.edgexfoundry.service: {{.Values.edgex.app.device.mqtt}}
    spec:
    {{- if and (eq .Values.edgex.security.enabled true) (or (eq .Values.edgex.storage.sharedVolumesAccessMode "ReadWriteOnce") (eq .Values.edgex.storage.useHostPath true))}}
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  org.edgexfoundry.service: {{ .Values.edgex.app.secretstoresetup}}
              topologyKey: "kubernetes.io/hostname"
    {{- end}}
      automountServiceAccountToken: false
      containers:
      - name: {{.Values.edgex.app.device.mqtt}}
        image: {{.Values.edgex.image.device.mqtt.repository}}:{{.Values.edgex.image.device.mqtt.tag}}
        imagePullPolicy: {{.Values.edgex.image.device.mqtt.pullPolicy}}
      {{- if .Values.edgex.security.enabled }}
        command: ["/edgex-init/ready_to_run_wait_install.sh"]
        args: ["/device-mqtt", "-cp=consul.http://edgex-core-consul:8500", "--registry", "--confdir=/res"]
      {{- end}}
        ports:
        - containerPort: {{.Values.edgex.port.device.mqtt}}
          name: "http"
      {{- if not .Values.edgex.security.enabled }}
        {{- if .Values.edgex.features.enableHostPort}}
          hostPort: {{.Values.edgex.port.device.mqtt}}
          hostIP: {{.Values.edgex.hostPortInternalBind}}
        {{- end}}
      {{- end}}
        env:
        - name: SERVICE_HOST
          value: {{.Values.edgex.app.device.mqtt}}
        - name: MQTTBROKERINFO_HOST
          value: {{.Values.edgex.app.mqttbroker}}
        envFrom:
        - configMapRef:
            name: edgex-common-variables
        - configMapRef:
            name: device-common-variables
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        startupProbe:
          httpGet:
            path: /api/v2/ping
            port: {{.Values.edgex.port.device.mqtt}}
          periodSeconds: 1
          failureThreshold: 120
        livenessProbe:
          httpGet:
            path: /api/v2/ping
            port: {{.Values.edgex.port.device.mqtt}}
      {{- if .Values.edgex.security.enabled }}
        volumeMounts:
        - mountPath: /edgex-init
          name: edgex-init
        - mountPath: /tmp/edgex/secrets
          name: edgex-secrets
      {{- end }}
      {{- if .Values.edgex.resources.device.usbcamera.enforceLimits }}
        resources:
          limits:
            memory: {{ .Values.edgex.resources.device.mqtt.limits.memory }}
            cpu: {{ .Values.edgex.resources.device.mqtt.limits.cpu }}
          requests:
            memory: {{ .Values.edgex.resources.device.mqtt.requests.memory }}
            cpu: {{ .Values.edgex.resources.device.mqtt.requests.cpu }}
      {{- end}}
      hostname: {{.Values.edgex.app.device.mqtt}}
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        runAsUser: {{ .Values.edgex.security.runAsUser }}
        runAsGroup: {{ .Values.edgex.security.runAsGroup }}
    {{- if .Values.edgex.security.enabled }}
      volumes:
      - name: edgex-init
        persistentVolumeClaim:
          claimName: edgex-init
      - name: edgex-secrets
        persistentVolumeClaim:
          claimName: edgex-secrets
    {{- end}}
