# Copyright (C) 2022 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.device.coap}}
  name: {{.Values.edgex.app.device.coap}}
spec:
  replicas: {{.Values.edgex.replicas.device.coap}}
  selector:
    matchLabels:
      org.edgexfoundry.service: {{.Values.edgex.app.device.coap}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        org.edgexfoundry.service: {{.Values.edgex.app.device.coap}}
    spec:
    {{- if and (eq .Values.edgex.security.enabled true) (or (eq .Values.edgex.storage.sharedVolumesAccessMode "ReadWriteOnce") (eq .Values.edgex.storage.useHostPath true))}}
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  org.edgexfoundry.service: {{ .Values.edgex.app.secretstoresetup}}
              topologyKey: "kubernetes.io/hostname"
    {{- end}}
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.imagePullSecrets }}
      - name: {{ . }}
      {{- end }}
    {{- end }}
      automountServiceAccountToken: false
      containers:
      - name: {{.Values.edgex.app.device.coap}}
        image: {{.Values.edgex.image.device.coap.repository}}:{{.Values.edgex.image.device.coap.tag}}
        imagePullPolicy: {{.Values.edgex.image.device.coap.pullPolicy}}
      {{- if .Values.edgex.security.enabled }}
        command: [ "/bin/sh", "/edgex-init/ready_to_run_wait_install.sh"]
        args:
          - "/device-coap"
          - "-cp=consul://edgex-core-consul:8500"
          - "--registry"
      {{- end}}
        ports:
        - containerPort: {{.Values.edgex.port.device.coap}}
          name: "http"
      {{- if not .Values.edgex.security.enabled }}
        {{- if .Values.edgex.features.enableHostPort}}
          hostPort: {{.Values.edgex.port.device.coap}}
          hostIP: {{.Values.edgex.hostPortInternalBind}}
        {{- end}}
      {{- end}}
        env:
        - name: SERVICE_HOST
          value: {{.Values.edgex.app.device.coap}}
        envFrom:
        - configMapRef:
            name: edgex-common-variables
        - configMapRef:
            name: edgex-device-c-sdk-environment
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        startupProbe:
          httpGet:
            path: /api/v3/ping
            port: {{.Values.edgex.port.device.coap}}
          periodSeconds: 1
          failureThreshold: 120
        livenessProbe:
          httpGet:
            path: /api/v3/ping
            port: {{.Values.edgex.port.device.coap}}
      {{- if .Values.edgex.security.enabled }}
        volumeMounts:
        - mountPath: /edgex-init
          name: edgex-init
        - mountPath: /tmp/edgex/secrets
          name: edgex-secrets
      {{- end }}
      {{- if .Values.edgex.resources.device.coap.enforceLimits }}
        resources:
          limits:
            memory: {{ .Values.edgex.resources.device.coap.limits.memory }}
            cpu: {{ .Values.edgex.resources.device.coap.limits.cpu }}
          requests:
            memory: {{ .Values.edgex.resources.device.coap.requests.memory }}
            cpu: {{ .Values.edgex.resources.device.coap.requests.cpu }}
      {{- end}}
      hostname: {{.Values.edgex.app.device.coap}}
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        runAsUser: {{ .Values.edgex.security.runAsUser }}
        runAsGroup: {{ .Values.edgex.security.runAsGroup }}
    {{- if .Values.edgex.security.enabled }}
      volumes:
      - name: edgex-init
        persistentVolumeClaim:
          claimName: edgex-init
      - name: edgex-secrets
        persistentVolumeClaim:
          claimName: edgex-secrets
    {{- end}}
