# Copyright (C) 2022 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
{{- if .Values.edgex.security.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.secretstoresetup}}
  name: {{.Values.edgex.app.secretstoresetup}}
spec:
  replicas: {{.Values.edgex.replicas.vault}}
  selector:
    matchLabels:
      org.edgexfoundry.service: {{.Values.edgex.app.secretstoresetup}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        org.edgexfoundry.service: {{.Values.edgex.app.secretstoresetup}}
    spec:
      {{- if and (eq .Values.edgex.security.enabled true) (eq .Values.edgex.storage.isLocal true)}}
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  org.edgexfoundry.service: {{ .Values.edgex.app.bootstrapper}}
              topologyKey: "kubernetes.io/hostname"
      {{- end}}
      automountServiceAccountToken: false
      containers:
      - name: {{.Values.edgex.app.secretstoresetup}}
        image: {{.Values.edgex.image.secretstoresetup.repository}}:{{.Values.edgex.image.secretstoresetup.tag}}
        imagePullPolicy: {{.Values.edgex.image.secretstoresetup.pullPolicy}}
        env:
        - name: EDGEX_USER
          value: "{{ .Values.edgex.security.runAsUser }}"
        - name: EDGEX_GROUP
          value: "{{ .Values.edgex.security.runAsGroup }}"
        # Remove SECRETSTORE_REVOKEROOTTOKENS later
        - name: SECRETSTORE_REVOKEROOTTOKENS
          value: "false"
        - name: ADD_SECRETSTORE_TOKENS
          value: "device-rest, device-virtual"
        - name: ADD_KNOWN_SECRETS
          value: "redisdb[app-rules-engine],redisdb[device-rest],redisdb[device-virtual]"
        envFrom:
        - configMapRef:
            name: edgex-common-variables
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        startupProbe:
          tcpSocket:
            port: {{ .Values.edgex.bootstrap.port.secretstoretokensready }}
          periodSeconds: 1
          failureThreshold: 120
        livenessProbe:
          tcpSocket:
            port: {{ .Values.edgex.bootstrap.port.secretstoretokensready }}
        volumeMounts:
          - mountPath: /edgex-init
            name: edgex-init
          - mountPath: /vault/config
            name: vault-config
          - mountPath: /tmp/edgex/secrets
            name: edgex-secrets
          - mountPath: /tmp/kong
            name: kong-tmp
          - mountPath: /run
            name: run-tmp
          - mountPath: /vault
            name: vault-tmp
      {{- if .Values.edgex.resources.secretstoresetup.enforceLimits }}
        resources:
          limits:
            memory: {{ .Values.edgex.resources.secretstoresetup.limits.memory }}
            cpu: {{ .Values.edgex.resources.secretstoresetup.limits.cpu }}
          requests:
            memory: {{ .Values.edgex.resources.secretstoresetup.requests.memory }}
            cpu: {{ .Values.edgex.resources.secretstoresetup.requests.cpu }}
      {{- end}}
      hostname: {{.Values.edgex.app.secretstoresetup}}
      restartPolicy: Always
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0
      volumes:
        - name: edgex-init
          persistentVolumeClaim:
            claimName: edgex-init
        - name: vault-config
          persistentVolumeClaim:
            claimName: vault-config
        - name: edgex-secrets
          persistentVolumeClaim:
            claimName: edgex-secrets
        - name: kong-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 8Mi
        - name: run-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 8Mi
        - name: vault-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 8Mi
{{- end}}
