[Writable]
  LogLevel = 'INFO'

  [Writable.StoreAndForward]
    Enabled = false
    RetryInterval = '5m'
    MaxRetryCount = 10

   [Writable.InsecureSecrets]
      [Writable.InsecureSecrets.NoPath]
        Path = ''
        [Writable.InsecureSecrets.NoPath.Secrets]
          username = 'nopath-user'
          password = 'nopath-pw'

      [Writable.InsecureSecrets.AWS]
        Path = '/aws'
        [Writable.InsecureSecrets.AWS.Secrets]
          username = 'aws-user'
          password = 'aws-pw'

      [Writable.InsecureSecrets.MongoDB]
        Path = 'mongodb'
        [Writable.InsecureSecrets.MongoDB.Secrets]
          username = ''
          password = ''

      [Writable.InsecureSecrets.Redis]
        Path = 'redisdb'
        [Writable.InsecureSecrets.Redis.Secrets]
          username = ''
          password = ''

[Service]
BootTimeout = '30s'
ClientMonitor = '15s'
CheckInterval = '10s'
Host = 'localhost'
Port = 48095
Protocol = 'http'
ReadMaxLimit = 100
StartupMsg = 'This is a sample Filter/XML Transform Application Service'
Timeout = '30s'

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Logging]
EnableRemote = false
File = ''

[Database]
Type = "redisdb"
Host = "localhost"
Port = 6379
Timeout = "30s"

# Shared Secret Store
[SecretStore]
  Host = 'localhost'
  Port = 8200
  Path = '/v1/secret/edgex/appservice/'
  # running the app natively uses Vault in dev mode (which uses HTTP)
  Protocol = 'http'
  TokenFile = './res/token.json'
  # Number of attempts to retry retrieving secrets before failing to start the service.
  AdditionalRetryAttempts = 10
  # Amount of time to wait before attempting another retry
  RetryWaitPeriod = "1s"

  [SecretStore.Authentication]
    AuthType = 'X-Vault-Token'

# Exclusive Secret Store
[SecretStoreExclusive]
  Host = 'localhost'
  Port = 8200
  Path = '/v1/secret/edgex/secrets-example/'
  # running the app natively uses Vault in dev mode (which uses HTTP)
  Protocol = 'http'
  TokenFile = './res/token.json'
  # Number of attempts to retry retrieving secrets before failing to start the service.
  AdditionalRetryAttempts = 10
  # Amount of time to wait before attempting another retry
  RetryWaitPeriod = "1s"

  [SecretStoreExclusive.Authentication]
    AuthType = 'X-Vault-Token'

[Clients]
  [Clients.CoreData]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48080

  [Clients.Logging]
  Protocol = "http"
  Host = "localhost"
  Port = 48061

[MessageBus]
Type = 'zero'
    [MessageBus.PublishHost]
        Host = '*'
        Port = 5564
        Protocol = 'tcp'
    [MessageBus.SubscribeHost]
        Host = 'localhost'
        Port = 5563
        Protocol = 'tcp'

# Choose either an HTTP trigger or MessageBus trigger (aka Binding)

[Binding]
Type="http"

#[Binding]
#Type="messagebus"
#SubscribeTopic="events"
#PublishTopic="somewhere"

[ApplicationSettings]
DeviceNames = "Random-Float-Device"
